<?php
/**
 * Created by PhpStorm.
 * User: ZhongHua
 * Date: 2018/3/12
 * Time: 21:15
 */
namespace app\admin\controller;
use think\Controller;

class Base extends Controller
{
    protected $filter = [
        'admin/user/login',
        'admin/user/checklogin',
        'admin/jump/toadminlogin',
    ];
    public function _initialize()
    {
//        TODO 完善RBAC判断
        parent::_initialize(); // TODO: Change the autogenerated stub
        $request = \think\Request::instance();
        $controller = strtolower($request->controller());
        $action = strtolower($request->action());
        $module = strtolower($request->module());
//        echo 222;
//        var_dump(session('uid'));exit;
        if (!session('?uid')) {
            if (!in_array($module . '/' . $controller . '/' . $action, $this->filter)) {
                $this->redirect('admin/jump/toadminlogin');
            }
        }
    }
}