<?php
/**
 * Created by PhpStorm.
 * User: ZhongHua
 * Date: 2018/5/9
 * Time: 10:59
 */
namespace app\index\controller;
use think\Controller;

class Base extends Controller
{
    protected $toLoginUrl = [
//        'index/ucenter',
//        'index/trade',
        'index/user/loginin',
        'index/user/checklogin',
        'index/user/register',
        'index/user/checkregister'
    ];
    /**
     * index模块初始化
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $request = \think\Request::instance();
        $controller = strtolower($request->controller());
        $action = strtolower($request->action());
        $module = strtolower($request->module());


        if (!session('uid') && !in_array($module . '/' . $controller . '/' . $action, $this->toLoginUrl)) {
//            未登录时跳转到登录
            $this->redirect('index/user/loginIn');
        }

    }

}